apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service-nodeport
spec:
  type: NodePort
  selector:
    app: nginx-multitool
  ports:
    - name: nginx-container-port
      protocol: TCP
      port: 9001
      targetPort: 80
      nodePort: 30001
    - name: multitool-container-port
      protocol: TCP
      port: 9002
      targetPort: 8080
      nodePort: 30002
