apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Изучаем ConfigMap</title>
    </head>
    <body>
        <h1>Данная страница подключена к nginx при помощи ConfigMap!</h1>
    </body>
    </html>
