{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_USER: {{ .Values.postgres.user | b64enc }}
  DB_PASSWORD: {{ .Values.postgres.password | b64enc }}
  DB_NAME: {{ .Values.postgres.db | b64enc }}
  POSTGRES_USER: {{ .Values.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
  POSTGRES_DB: {{ .Values.postgres.db | b64enc }}
{{- end }}