---
- name: Install Clickhouse
  become: true
  hosts: clickhouse
  handlers:
    - name: Restart clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Install dependencies for itself
      ansible.builtin.apt:
        name:
          - python3-apt
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: true

    - name: Add clickhouse GPG key
      ansible.builtin.get_url:
        url: "{{ clickhouse_gpg_key_url }}"
        dest: /tmp/clickhouse_key
        mode: '0644'

    - name: Convert GPG key to GPG format
      ansible.builtin.command:
        cmd: "gpg -o /usr/share/keyrings/clickhouse-keyring.gpg --dearmor /tmp/clickhouse_key"
      args:
        creates: /usr/share/keyrings/clickhouse-keyring.gpg

    - name: Add clickhouse deb repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/clickhouse.list
        line: 'deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg] {{ clickhouse_repo_url }} stable main'
        create: true
        mode: '0644'

    - name: Update packages list
      ansible.builtin.apt:
        update_cache: true

    - name: Install clickhouse
      ansible.builtin.apt:
        name: "{{ item }}={{ clickhouse_version }}"
        state: present
      with_items: "{{ clickhouse_packages }}"
      register: install_ch
      notify: Restart clickhouse service

    - name: Make Clickhouse available over network for specified hosts
      ansible.builtin.template:
        src: ./templates/clickhouse_listen_hosts.xml.j2
        dest: /etc/clickhouse-server/config.d/listen_hosts.xml
        mode: "0644"
        owner: clickhouse
        group: clickhouse
      notify: Restart clickhouse service

    - name: Ensure clickhouse-server systemd enabled & started
      ansible.builtin.systemd:
        name: clickhouse-server
        enabled: true
        daemon_reload: true
        state: started

    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database {{ clickhouse_database_name }}'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

    - name: Create table
      ansible.builtin.command: >
        clickhouse-client -q "
        CREATE TABLE {{ clickhouse_database_name }}.{{ clickhouse_table_name }} {{ clickhouse_table_field_options }}"
      register: create_table
      failed_when: create_table.rc != 0 and create_db.rc !=82
      changed_when: create_table.rc == 0

- name: Install Vector
  become: true
  hosts: vector
  handlers:
    - name: Restart vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - name: Create Vector user
      ansible.builtin.user:
        name: vector
        state: present
        shell: /bin/bash

    - name: Downlaod Vector
      ansible.builtin.get_url:
        url: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz
        dest: /tmp/vector.tar.gz
        mode: "0644"

    - name: Extract Vector
      ansible.builtin.unarchive:
        src: /tmp/vector.tar.gz
        dest: /tmp/
        remote_src: true

    - name: Copy Vector binary
      ansible.builtin.copy:
        src: /tmp/vector-x86_64-unknown-linux-gnu/bin/vector
        dest: /usr/bin/vector
        mode: '0755'
        remote_src: true
        owner: vector
        group: vector

    - name: Create vector config directory
      ansible.builtin.file:
        path: /etc/vector
        state: directory
        owner: vector
        group: vector
        mode: "0755"

    - name: Create vector data directory
      ansible.builtin.file:
        path: /var/lib/vector
        state: directory
        owner: vector
        group: vector
        mode: "0755"

    - name: Generate Vector configuration
      ansible.builtin.template:
        src: ./templates/vector_config.yaml.j2
        dest: /etc/vector/vector.yaml
        mode: "0644"
        owner: vector
        group: vector
      notify: Restart vector service

    - name: Ensure systemd vector service exist
      ansible.builtin.template:
        src: ./templates/vector.service.j2
        dest: "/etc/systemd/system/vector.service"
        force: true
        mode: "0644"
      notify: Restart vector service

    - name: Ensure Vector systemd enabled & started
      ansible.builtin.systemd:
        name: vector.service
        enabled: true
        daemon_reload: true
        state: started

- name: Install nginx
  become: true
  hosts: nginx,lighthouse,vector
  handlers:
    - name: Restart nginx service
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
  tasks:
    - name: Install dependencies for itself
      ansible.builtin.apt:
        name:
          - python3-apt
          - apt-transport-https
          - software-properties-common
        state: present
        update_cache: true

    - name: Add Nginx signing key
      ansible.builtin.apt_key:
        url: https://nginx.org/keys/nginx_signing.key
        state: present

    - name: Add Nginx repository
      ansible.builtin.apt_repository:
        repo: "deb https://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx"
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Nginx
      ansible.builtin.apt:
        name: "nginx"
        state: present

    - name: Ensure Nginx is started and enabled
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true

    - name: Change permissions of default access.log
      ansible.builtin.file:
        path: /var/log/nginx/access.log
        mode: "0644"

- name: Install and configure Lighthouse
  hosts: lighthouse
  become: true
  handlers:
    - name: Restart nginx service
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
  tasks:
    - name: Install dependencies for itself
      ansible.builtin.apt:
        name:
          - python3-apt
          - python3-pip
          - git
        state: present
        update_cache: true

    - name: Check if Lighthouse directory already exists
      ansible.builtin.stat:
        path: /opt/lighthouse
      register: lighthouse_dir

    - name: Clone Lighthouse repository
      ansible.builtin.git:
        repo: 'https://github.com/VKCOM/lighthouse.git'
        dest: '/opt/lighthouse'
        version: master
      when: not lighthouse_dir.stat.exists

    - name: Change ownership of Lighthouse directory
      ansible.builtin.file:
        path: /opt/lighthouse
        owner: www-data
        group: www-data
        recurse: true
        state: directory

    - name: Generate Nginx configuration for Lighthouse
      ansible.builtin.template:
        src: ./templates/lighthouse_nginx_config.conf.j2
        dest: /etc/nginx/conf.d/lighthouse.conf
        mode: "0644"
      notify: Restart nginx service

    - name: Delete nginx default configuration file if exists
      ansible.builtin.file:
        path: /etc/nginx/conf.d/default.conf
        state: absent
      notify: Restart nginx service
