apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Secure Web Page with Using K8S Secrets</title>
    </head>
    <body>
        <h1>Welcome to My Secure Web Page!</h1>
        <p>This page is served over HTTPS</p>
    </body>
    </html>
